Repository Cloudweb1/subway_back, pull requests merged in 2024-10, with the labels that each got.

#1 [Docx] 이슈 템플릿, 풀리퀘스트 템플릿 추가
  .github/ISSUE_TEMPLATE/issue---label-아래에서-맞는-키워드-넣어주세요----만들-기능-이름-적어주세요-.md
  .github/pull_request_template.md
Labels: documentation

#7 feat/#6 add CORS header
  app.js
Labels: feat

#9 [Fix]#2 fix error
  bin/www.js
  utils/metro/arrivals.js
  utils/metro/stationDelta.js
Labels: fix
